### ISSUE TITLE
Fails to build on rustc 1.53.0-nightly (f82664191 2021-03-21)

### ISSUE THREAD

**Issue by lambda-fairy** [jhpratt/standback#11]
See https://github.com/lambda-fairy/maud/runs/2162452518

```
error[E0432]: unresolved import `core::task::Wake`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/standback-0.2.16/src/lib.rs:520:13
    |
520 |     pub use core::task::Wake;
    |             ^^^^^^^^^^^^----
    |             |           |
    |             |           help: a similar name exists in the module (notice the capitalization): `wake`
    |             no `Wake` in `task`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `standback`
```

**Comment by lambda-fairy** [comment]
It looks like `Wake` is available in `std` but not `core` ?

https://doc.rust-lang.org/nightly/std/task/trait.Wake.html
https://doc.rust-lang.org/nightly/core/task/index.html

**Comment by jhpratt** [comment]
Yup, this is absolutely correct. `Wake` relies on `Arc`, which isn't available in `core`. I'll fix this and have a patch out soon, yanking the existing version.

**Comment by jhpratt** [comment]
Fix is out as standback 0.2.17, with 0.2.16 yanked. Minor oversight when I put `core` instead of `std`.

Thanks for the report!

**Comment by lambda-fairy** [comment]
Thanks Jacob!

**Comment by FloxD** [comment]
in case anyone else stumbles across this issue and is wondering how to fix this:
a simple `cargo update` should fix the issue
